name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Lint/Tests
      run: npm test
    
    # Upload dos relatórios de testes como artifacts
    - name: Upload Test Logs
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: tests/output/ # Substitua pelo diretório onde os logs são gerados

    - name: Build Application
      run: |
        echo "Build process goes here."
        npm run build

    # Upload do build como artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-build
        path: dist/ # Substitua pelo diretório onde o build é gerado

    # Upload de arquivos adicionais
    - name: Upload Configuration Files
      uses: actions/upload-artifact@v3
      with:
        name: config-files
        path: |
          package.json
          .env
          
